name: TravelFix
description: TravelFix

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  google_maps_flutter: ^0.5.25
  den_lineicons: #^0.0.3
    path: ./packages/den_lineicons
  dependencies:
  flutter_svg: ^0.17.1
  http: ^0.12.0+4
  flutter_spinkit: "^4.1.1"
  url_launcher: "^5.4.1"
  html: ^0.14.0+3
  cached_network_image: ^2.0.0
  collection: ^1.14.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/launch/app_logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/Jost-Book.ttf
        - asset: assets/fonts/Jost/Jost-Hairline.ttf
          weight: 100
        - asset: assets/fonts/Jost/Jost-HairlineItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Jost/Jost-Thin.ttf
          weight: 200
        - asset: assets/fonts/Jost/Jost-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Jost/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost/Jost-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Jost/Jost-BookItalic.ttf
          style: italic
        - asset: assets/fonts/Jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost/Jost-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Jost/Jost-Semi.ttf
          weight: 600
        - asset: assets/fonts/Jost/Jost-SemiItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Jost/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost/Jost-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Jost/Jost-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Jost/Jost-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Jost/Jost-Black.ttf
          weight: 900
        - asset: assets/fonts/Jost/Jost-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    # photos
    - assets/photos/
    # Localization
    - i18n/en.json
    # icon
    - assets/iconGolo/
    - assets/app/launch/